# Numpy

Hoje, vamos começara ver a biblioteca matemática mais importante pro ecossistema 
científico do Python: O Numpy.

Vamos relembrar alguns conceitos

A biblioteca **NumPy** _(Numerical Python)_ proporciona uma forma eficiente de armazenagem e processamento de conjuntos de dados, e é utilizada como base para a construção da biblioteca Pandas, que estudaremos a seguir.

O diferencial do Numpy é sua velocidade e eficiência, o que faz com que ela seja amplamente utilizada para computação científica e analise de dados. 

A velocidade e eficiência é possível graças à estrutura chamada **numpy array**, que é um forma eficiente de guardar e manipular matrizes, que serve como base para as tabelas que iremos utilizar.

In [3]:
# A gente importa o numpy sempre chamando ele de "np"
import numpy as np

In [2]:
# Vamos fazer uma comparação com uma lista de Python
py_array = [[1,2,3]]

print(py_array)
print(type(py_array))

[[1, 2, 3]]
<class 'list'>


In [3]:
# Uma lista com 2 dimensões é uma lista de listas

print(type(py_array[0]))

<class 'list'>


In [4]:
# Nota como o tipo da variável muda para "ndarray"

np_array = np.array(py_array)

print(np_array)
print(type(np_array))

[[1 2 3]]
<class 'numpy.ndarray'>


In [8]:
py_array_string = [['a',1,2]]
np_array_string = np.array(py_array_string)

print(np_array_string)
print(type(np_array_string))
print(np_array_string.dtype)

[['a' '1' '2']]
<class 'numpy.ndarray'>
<U21


In [ ]:
# Mas no  numpy, um ndarray continua sendo formado de ndarrays.

In [ ]:
# 3 atributos básicos pra um ndarray

In [9]:
# O dtype de um array do numpy pode ser controlado na hora que a gente cria.

py_array = [1,2,3]

array_int = np.array(py_array, dtype=np.float64)

In [10]:
print(array_int)
print(array_int.dtype)

[1. 2. 3.]
float64


In [ ]:
# Mas quando a gente não define, ele infere a partir dos nossos dados.

In [ ]:
# Para selecionar um elemento de uma tabela no Python e no Numpy, tem uma ligeira diferença.

**Revisando**

In [ ]:
# No Python, existe o conceito de "indexing", que é pegar elementos pelo seu índice (a sua posição) 

In [ ]:
# Também existe uma forma de pegar um subconjunto da lista.
# A gente chama isso de "slicing". Nota que o último elemento não entra!

In [19]:
# Invertendo lista

# Maneira 1
lista = [1,2,3,4,5,6,7,8,9]
lista_reversa_obj = reversed(lista)
print(list(lista_reversa_obj))

# Maneira 2
lista2 = [1,2,3,4,5,6,7,8,9]
lista2.reverse()
print(lista2)

# Maneira 3
lista3 = [1,2,3,4,5,6,7,8,9]
print(lista3[::-1])


[9, 8, 7, 6, 5, 4, 3, 2, 1]
[9, 8, 7, 6, 5, 4, 3, 2, 1]
[9, 8, 7, 6, 5, 4, 3, 2, 1]


In [ ]:
# Podemos definir um início também pro slicing.
# Quando não colocamos nada, ele assume que o início é 0.
# No caso do fim, se não colocamos nada, ele assume que o fim é o último elemento.

In [ ]:
# O poder do slicing é que a gente pode definir diferentes tamanhos de passo.

Também podemos aplicar o conceito do slicing no numpy

**Funções numpy**  
O numpy também tem diversas funções para facilitar criação de arrays.

In [8]:
print(np.zeros(10))
print(np.ones(5))


# Observações

#Matriz identitária preenche a diagonal com 1 e o resto 0. Ela também é uma matriz quadrada, com mesma quantidade de linhas e colunas
print(np.identity(4))

#Matriz de olho, quando não há a quantidade de números corretos, ela preenche só com o que tem
print(np.eye(4,3))


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [5]:
# Relembrando a função range

list(range(2,10))

# Aplicando slice
list(range(2,10,2))


[2, 4, 6, 8]

In [10]:
# Também podemos fazer listas de números.

print(np.arange(2,10,2))

print(np.arange(10.5,30.5,10))

[2 4 6 8]
[10.5 20.5]


In [11]:
print(np.linspace(10,30,10))

[10.         12.22222222 14.44444444 16.66666667 18.88888889 21.11111111
 23.33333333 25.55555556 27.77777778 30.        ]


# Operações Básicas

In [13]:
# Se a força do numpy é ter tudo operando como vetores, 
# então ele tem que ter operações de vetores.

vetor1 = np.arange(0,10)
vetor2 = np.arange(0,20,2)

print(vetor1)
print(vetor2)

[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10 12 14 16 18]


In [14]:
# Soma por elemento

# soma cada valor do vetor individualmente

print(vetor1 + vetor2)

[ 0  3  6  9 12 15 18 21 24 27]


In [15]:
# Multiplicação elemento por elemento

# multiplica cada valor do vetor individualmente

print(vetor1 * vetor2)

[  0   2   8  18  32  50  72  98 128 162]


In [17]:
# produto de matrizes (neste caso, produto escalar)
# Isso é multiplicar elemento por elemento, e depois somar

print((vetor1 * vetor2).sum())

print(vetor1 @ vetor2)

570
570


## Bora praticar!

1) Inverta um vetor (o primeiro elemento vira o último). Para testar crie um vetor a partir da seguinte lista [0, 5, 1, 9, 9, 87]

In [44]:
# Maneira 1
vetor = [0, 5, 1, 9, 9, 87]
print(vetor[::-1])

# Maneira 2
vetor2 = [0, 5, 1, 9, 9, 87]
vetor2.reverse()
print(vetor2)

# Maneira 3
vetor3 = [0, 5, 1, 9, 9, 87]
vetor3_obj = reversed(vetor3)
print(list(vetor3_obj))

# Maneira 4
vetor4 = [0, 5, 1, 9, 9, 87]
vetor4_invert = np.array(vetor4[::-1])
print(vetor4_invert)


[87, 9, 9, 1, 5, 0]
[87  9  9  1  5  0]
[87, 9, 9, 1, 5, 0]
[87, 9, 9, 1, 5, 0]


2) Crie um vetor com valores que vão de 1 até 21 de dois em dois, a partir da função arange

In [27]:
print(np.arange(1,22,2))

[ 1  3  5  7  9 11 13 15 17 19 21]


3) Ache os índices dos elementos não-zero a partir do array [1,2,0,0,4,0]

In [68]:
array = np.array([1,2,0,0,4,0])

indice_nao_zero = np.nonzero(array)[0]
# ou
indice_nao_zero2 = np.where(array != 0)[0]

print(indice_nao_zero)
print(indice_nao_zero2)

[0 1 4]
[0 1 4]


E se a gente quisesse pegar os elementos diferentes de zero?

In [36]:
#elementos_nao_zero1 = np.where(array != 0)[0]
array = np.array([1,2,0,0,4,0])
elementos_nao_zero = array[array != 0]
print(elementos_nao_zero)

[1 2 4]


4) Crie uma matriz identidade 3x3

In [39]:
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


5) Crie um array de 10 com valores aleatórios 

In [51]:
array_aleatorio_0_1 = np.random.rand(10)
print(array_aleatorio_0_1)


[0.42570523 0.20855894 0.09457377 0.57432516 0.61540708 0.32564659
 0.4733843  0.63723033 0.18725518 0.85685645]


6) Crie um array 100 com valores aleatórios e ache os valores máximo e mínimo

In [49]:

array_inteiro_aleatorio = np.random.randint(1, 101, size=100)

maximo = np.max(array_inteiro_aleatorio)
minimo = np.min(array_inteiro_aleatorio)
print(array_inteiro_aleatorio)
print(f'valor maximo: {maximo}')
print(f'valor minimo: {minimo}')

[51 54 15 80 81 57 99 39 70 61 54 17 48 65 49 74 80 53 93 97 92 46 23 47
  9 51 12 32 70 44 23 60 68  7 26 95  6 17 50 69 63 67 30 46 86 73  3 14
 80 19 65 20 56 40 87  9 71 40 19 71  3 39 17 57 38 37 79 31 29 31 72 74
 94 76 68 72 33  6 77 47 67 43 68 22 97 38 97 51  2 68  3 53 73 11 16 26
 88 11  2 87]
valor maximo: 99
valor minimo: 2


7) Crie um array 2D (bidimensional) com 1 na borda e 0 dentro

In [1]:
linhas = 5
colunas = 5

matriz_2d = np.ones((linhas, colunas))

matriz_2d[1:-1,1:-1] = 0
print(matriz_2d)

NameError: name 'np' is not defined

8) Crie uma matriz 5x5 com valores 1, 2, 3, 4 logo abaixo da diagonal

In [11]:
matriz = np.zeros((5, 5))
for i in range(1, 5):
    matriz[i, i - 1] = i
print(matriz)

# ou
oito = np.diag([1, 2, 3, 4], k=-1)
print(oito)


[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


## Mini tarefa

Utilizando o numpy crie dois vetores a partir das listas ```lista_1 = [1, 2, 3, 4]``` e ```lista_2 = [12, 6, 0, 29]``` e calcule o produto escalar entre esses dois vetores. Responda no [link](https://forms.gle/oz5cHCfj5yQFWw6a9).

In [69]:
lista_1 = [1, 2, 3, 4]
lista_2 = [12, 6, 0, 29]

vetor_1 = np.array(lista_1)
vetor_2 = np.array(lista_2)

produto_escalar = np.dot(vetor_1, vetor_2)

print("Vetor 1:", vetor_1)
print("Vetor 2:", vetor_2)
print("Produto escalar:", produto_escalar)

Vetor 1: [1 2 3 4]
Vetor 2: [12  6  0 29]
Produto escalar: 140
